services:
  facenet-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: facenet-recognition
    ports:
      - "7100:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
    restart: unless-stopped
    # 移除了healthcheck部分